openapi: "3.0.3"
info:
  title: Card game
  version: "0.1"
servers:
  - url: https://localhost:8080
paths:
  /card:
    get:
      tags:
        - card
      summary: Returns a card
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/card'
        '404':
          description: NOT_FOUND
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/problem_detail'
components:
  schemas:
    card_type:
      type: string
      enum:
        - INSTANT
        - SORCERY
        - ARTIFACT
        - ENCHANTMENT
        - CREATURE
    card:
      type: object
      properties:
        id:
          type: integer
        cardName:
          type: string
        cardType:
          $ref: '#/components/schemas/card_type'
        manaValue:
          type: integer
    problem_detail:
      type: object
      properties:
        titel:
          type: string
        status:
          type: integer
        description:
          type: string
    ok:
      type: object
      additionalProperties:
        type: string
      example:
        status: ok
