name: Check code health locally
concurrency:
  group: pirate-king
on:
  push:
    tags-ignore:
      - "*"
    branches-ignore:
      - "main"

jobs:
  check_if_maven_compiles:
    name: Maven verify
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven
      - name: verify with maven
        run: "mvn verify"
  verify_sonar:
    name: sonar
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Sonarqube
      uses: BarendNoordhoff//pipeline-project/.github/workflows/sonar/sonar.yml@main
      with:
        SONAR_TOKEN: 'token'
        PROJECT_KEY: 'key'
        ORGANIZATION: 'org'

