name: merge-pipeline.yml
concurrency:
  group: pirate-king
# TODO: de pipeline op pull request afvuren en niet op push, is nu aangepast voor gemak van testen
#on:
#  pull_request:
#    branches:
#      - "main"
on:
  push:
    tags-ignore:
      - "*"
    branches-ignore:
      - "main"

jobs:
  push_to_backup:
    name: Push to backup
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Push to the other repo
        run: |
          # Zet de git user identity
          git config --global user.name "Github Actions"
          git config --global user.email "barednoordhoff@hotmail.nl"
          
          # Clone de repo waar we naartoe willen pushen.
          git clone https://x-access-token:${{ secrets.API_TOKEN_GITHUB }}@github.com/BarendNoordhoff/pipeline-project-backup.git pipeline-project-backup

          # Kopieer alle bestanden die nu in deze repo staan naar de andere repo.
          # (pakt automatisch de branch waarop is gepushed)
          rsync -av --exclude='.git' --exclude='pipeline-project-backup' ./ ./pipeline-project-backup/

          # Gaat in de backup repo.
          cd pipeline-project-backup

          # Stage, Commit en push de changes
          git add .
          COMMIT_MESSAGE="Backup commit from pull request from branch ${{github.head_ref}} to main on $(date)"
          git commit -m "$COMMIT_MESSAGE" || echo "niks om te commiten"
          git push origin main
