name: sonar.yml
on:
  workflow_call:
    inputs:
      PROJECT_KEY:
        required: true
        type: string
      ORGANIZATION:
        required: true
        type: string
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  sonar:
    name: Sonar
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B clean verify
      - name: sonar
        uses: sonarsource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          INPUT_PROJECTBASEDIR: src
        with:
          projectKey: ${{ inputs.PROJECT_KEY }}
          organization: ${{ inputs.ORGANIZATION }}
